line-length = 110
target-version = "py310"

exclude = [
    "*_build/",
    "platform/extern/HiCR/",
    "platform/extern/TaskR/",
    "pypto-lib/",
]

[lint]
select = [
    "F",
]
ignore = [
    "F841",
]
